### ISSUE TITLE
System.NullReferenceException:“Object reference not set to an instance of an object.”  customer is null。

### ISSUE THREAD

**Issue by jimnycat** [DevExpress-Examples/XPO_how-to-implement-odata4-service-with-xpo-netcore#8]
A null reference exception occurred when I sent a post request with Postman debugging
`[HttpPost]
        public IActionResult Post([FromBody]Customer customer) {
            if(!ModelState.IsValid) {
                return BadRequest();
            }
            Customer entity = new Customer(Session) {
                CustomerID = customer.CustomerID,
                CompanyName = customer.CompanyName
            };
            Session.CommitChanges();
            return Created(entity);
        }`

**Comment by Uriahas** [comment]
Hello,

We cannot reproduce this error in a simple project. Please submit a ticket in our [Support Center](https://supportcenter.devexpress.com/) and include error details (callstack, steps to reproduce). We will be happy to help you.
